# Generated by Django 5.2.12 on 2026-04-01 21:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('sucursal', 'Sucursal Principal'), ('puesto', 'Puesto Mayoreo')], default='sucursal', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(choices=[('bulto', 'Bulto'), ('caja', 'Caja'), ('kg', 'Kilogramo'), ('litro', 'Litro'), ('pieza', 'Pieza')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PanFrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('cantidad_piezas', models.PositiveIntegerField(help_text='Total de pan sobrante reunido ese día', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_remate', models.DecimalField(decimal_places=2, help_text='Precio por bolsa/lote de pan frío', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('vendido', models.BooleanField(default=False, help_text='¿Ya se vendió este lote?')),
                ('ingreso_generado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dinero real que entró al vender el pan frío', max_digits=10)),
            ],
            options={
                'verbose_name': 'Pan Frío',
                'verbose_name_plural': 'Pan Frío',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_publico', models.DecimalField(decimal_places=2, help_text='Precio en sucursal principal', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_mayoreo', models.DecimalField(decimal_places=2, help_text='Precio al que se le da a los puestos', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_sucursal', models.PositiveIntegerField(default=0)),
                ('es_temporada', models.BooleanField(default=False, help_text='Pan especial de temporada (Día de Muertos, Navidad…)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cuántos bultos / cajas / kg se compraron', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('costo_total', models.DecimalField(decimal_places=2, help_text='Cuánto se pagó en total por esa compra', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='panaderia.insumo')),
            ],
            options={
                'verbose_name': 'Compra de Insumo',
                'verbose_name_plural': 'Compras de Insumos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PedidoMayoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('cantidad_entregada', models.PositiveIntegerField(help_text='Total de piezas que se llevó (producción + préstamo)', validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_regresada', models.PositiveIntegerField(default=0, help_text='Pan que devolvió al final del día')),
                ('prestado_de_sucursal', models.PositiveIntegerField(default=0, help_text='Piezas tomadas del mostrador para completar el pedido')),
                ('monto_recibido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dinero que entregó el empleado al ajustar cuentas', max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_mayoreo', to='panaderia.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_mayoreo', to='panaderia.producto')),
            ],
            options={
                'verbose_name': 'Pedido Mayoreo',
                'verbose_name_plural': 'Pedidos Mayoreo',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True, default='')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_sucursal', to='panaderia.empleado')),
            ],
            options={
                'verbose_name': 'Venta Sucursal',
                'verbose_name_plural': 'Ventas Sucursal',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('piezas_producidas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='panaderia.producto')),
            ],
            options={
                'verbose_name': 'Producción Diaria',
                'verbose_name_plural': 'Producción Diaria',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'producto')},
            },
        ),
    ]
