# Generated by Django 5.2.12 on 2026-04-13 00:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0002_alter_producciondiaria_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidomayoreo',
            name='cantidad_entregada',
        ),
        migrations.RemoveField(
            model_name='pedidomayoreo',
            name='cantidad_regresada',
        ),
        migrations.RemoveField(
            model_name='pedidomayoreo',
            name='prestado_de_sucursal',
        ),
        migrations.RemoveField(
            model_name='pedidomayoreo',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedidomayoreo',
            name='destino',
            field=models.CharField(choices=[('mercado', 'Mercado'), ('la_burgos', 'La Burgos')], default='mercado', help_text='¿A dónde se lleva el pan?', max_length=30),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(choices=[('bulto', 'Bulto'), ('caja', 'Caja'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('litro', 'Litro'), ('pieza', 'Pieza')], max_length=20),
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cantidad_entregada', models.PositiveIntegerField(help_text='Piezas que se llevó', validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_regresada', models.PositiveIntegerField(default=0, help_text='Piezas que devolvió al final del día')),
                ('prestado_de_sucursal', models.PositiveIntegerField(default=0, help_text='Piezas tomadas del mostrador')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='panaderia.pedidomayoreo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_pedido', to='panaderia.producto')),
            ],
            options={
                'verbose_name': 'Línea de Pedido',
                'verbose_name_plural': 'Líneas de Pedido',
            },
        ),
        migrations.CreateModel(
            name='ConteoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('cantidad_contada', models.PositiveIntegerField(help_text='Piezas contadas al final del día')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='panaderia.producto')),
            ],
            options={
                'verbose_name': 'Conteo Sucursal',
                'verbose_name_plural': 'Conteos Sucursal',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'producto'), name='unique_conteo_sucursal')],
            },
        ),
    ]
