# Generated by Django 5.2.12 on 2026-04-13 00:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0003_remove_pedidomayoreo_cantidad_entregada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BolsaPanFrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha_registro', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('precio_remate', models.DecimalField(decimal_places=2, help_text='Precio total de la bolsa armada', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('vendido', models.BooleanField(default=False, help_text='¿Ya se vendió esta bolsa?')),
                ('ingreso_generado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dinero que entró al vender la bolsa', max_digits=10)),
            ],
            options={
                'verbose_name': 'Bolsa de Pan Frío',
                'verbose_name_plural': 'Bolsas de Pan Frío',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.RemoveField(
            model_name='panfrio',
            name='producto',
        ),
        migrations.CreateModel(
            name='InventarioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('conteo_apertura', models.PositiveIntegerField(default=0, help_text='Pan inicial en la mañana')),
                ('conteo_cierre', models.PositiveIntegerField(blank=True, help_text='Pan sobrante en la noche', null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_diarios', to='panaderia.producto')),
            ],
            options={
                'verbose_name': 'Inventario Diario',
                'verbose_name_plural': 'Inventarios Diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LineaBolsaPanFrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cantidad', models.PositiveIntegerField(help_text='Piezas de este producto ingresadas en la bolsa', validators=[django.core.validators.MinValueValidator(1)])),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='panaderia.bolsapanfrio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_pan_frio', to='panaderia.producto')),
            ],
            options={
                'verbose_name': 'Línea de Bolsa Fría',
                'verbose_name_plural': 'Líneas de Bolsa Fría',
            },
        ),
        migrations.DeleteModel(
            name='ConteoSucursal',
        ),
        migrations.DeleteModel(
            name='PanFrio',
        ),
        migrations.AddConstraint(
            model_name='inventariodiario',
            constraint=models.UniqueConstraint(fields=('fecha', 'producto'), name='unique_inventario_diario'),
        ),
    ]
