# Generated by Django 5.2.13 on 2026-04-19 21:28

import django.core.validators
import django.db.models.deletion
import panaderia.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0004_bolsapanfrio_remove_panfrio_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='cantidad_desde_produccion',
            field=models.PositiveIntegerField(default=0, help_text='Fase 2: piezas tomadas del pool Producción del Día.'),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='cantidad_desde_stock_principal',
            field=models.PositiveIntegerField(default=0, help_text='Fase 2: piezas tomadas del Stock Sucursal Principal.'),
        ),
        migrations.AlterField(
            model_name='bolsapanfrio',
            name='fecha_registro',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comprainsumo',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventariodiario',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedidomayoreo',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producciondiaria',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ConsolidacionProduccionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha', models.DateField(db_index=True, unique=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidaciones_produccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consolidación producción → principal',
                'verbose_name_plural': 'Consolidaciones producción',
            },
        ),
        migrations.CreateModel(
            name='ConsumoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_internos', to='panaderia.producto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_internos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consumo interno',
                'verbose_name_plural': 'Consumos internos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionPanPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha_registro', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('destino', models.CharField(blank=True, choices=[('mercado', 'Mercado'), ('la_burgos', 'La Burgos')], default='', help_text='Puesto o ruta asociada a la devolución.', max_length=30)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_pan_frio', to='panaderia.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_desde_puesto', to='panaderia.producto')),
            ],
            options={
                'verbose_name': 'Devolución pan (puesto)',
                'verbose_name_plural': 'Devoluciones pan desde puestos',
                'ordering': ['-fecha_registro', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaldoPanDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('saldo_produccion_disponible', models.PositiveIntegerField(default=0, help_text='Pool A: piezas del horno del día aún no consolidadas.')),
                ('saldo_stock_principal', models.PositiveIntegerField(default=0, help_text='Pool B: piezas en sucursal principal (mostrador / reserva).')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_pan_dia', to='panaderia.producto')),
            ],
            options={
                'verbose_name': 'Saldo pan por día',
                'verbose_name_plural': 'Saldos de pan por día',
                'ordering': ['-fecha', 'producto__nombre'],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'producto'), name='unique_saldo_pan_dia_fecha_producto')],
            },
        ),
    ]
