# Generated by Django 5.2.13 on 2026-04-19 22:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0005_fase1_y_modelos_fase2_3'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='lineapedido',
            name='cantidad_desde_produccion',
        ),
        migrations.RemoveField(
            model_name='lineapedido',
            name='cantidad_desde_stock_principal',
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_produccion',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='Costo aproximado de hacer el pan', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.DeleteModel(
            name='ConsolidacionProduccionDiaria',
        ),
        migrations.DeleteModel(
            name='ConsumoInterno',
        ),
        migrations.DeleteModel(
            name='DevolucionPanPuesto',
        ),
        migrations.DeleteModel(
            name='SaldoPanDia',
        ),
    ]
